# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf69958ff93ce7052b9ae211b01fa134b4de20a6d987de66b3e064b376502c17d352fc4a9c651122f0003d5a44af95a75f63c603414127ca2be0081461a2d0b

test:
  secret_key_base: c9f67d21c821bfa0c0b90b9a038d63b065eb8b27f8c0a40c64768e487a35bee294b1d1e2a107e58bdbc62b811045bb2df559d52e403a2c0f1688d56b5f4e8081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
